### ISSUE TITLE
Create network delay with port parmeter in docker cause can’t reach any address

### ISSUE THREAD

**Issue by lanixzcj** [chaosblade-io/chaosblade#204]
## Issue Description

Type: bug report

#### 1. run create network delay with port
blade create network delay --destination-ip x.x.x.x --remote-port xxx --interface eth0 --time xx
### Describe what you expected to happen

delay time for specify port 

### How to reproduce it (as minimally and precisely as possible)

see `Describe what happened`

#### 1.Host OS
Mac 10.13.6
#### 2.Docker Image
openjdk:8-jre
#### 3.Docker core version: uname -a
Linux e40512f08508 4.9.125-linuxkit # 1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
#### 4.Docker ip env: ip a
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
290: eth0@if291: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```
#### 5.cat /sys/class/net/eth0/tx_queue_len
0

**Comment by xcaspar** [comment]
@lanixzcj 
The reason for this problem is that the 4.9 version of the kernel when setting qdisc, go to `__dev_queue_xmit` before attempting to send the package, it will enter prio qdisc, where prio qdisc will put skb into the queue, because len's queue len is 0, resulting in Skb is taken directly to kfree_skb_list and released directly.

The solution is to read the value of `/sys/class/net/$device/tx_queue_len` before executing the tc command. If it is greater than 0, it will not be processed. If the file is not found or is less than or equal to 0, execute `ifconfig eth0 txqueuelen 1000` command.

**Comment by lanixzcj** [comment]
It works. Thanks for your support ！！

**Comment by xcaspar** [comment]
Related issue: #106
