### ISSUE TITLE
 Mutual influence when different CPU are fullload with experimental destroy

### ISSUE THREAD

**Issue by 86542822** [chaosblade-io/chaosblade#46]
The server has N CPUs
Mount one of the CPUs fullload
./blade create cpu fullload --numcpu 1
{"code":200,"success":true,"result":"51d50db1faf4fb80"}

Then mount one of the CPUs fullload
./blade create cpu fullload --numcpu 1
{"code":200,"success":true,"result":"96a4b01617f5f2f7"}

Destroy one of the mount experiments
./blade destroy 51d50db1faf4fb80

At this time, both CPU mount experiments will be destroyed.

**Comment by zousheng** [comment]
Just verified this issue still exists in 0.4.0 version, I will fix this asap

**Comment by Super-long** [comment]
I get it!

I figured out the problem after I followed the dlv to debug the entire life cycle of a destroy. This bug appears in chaosblade-exec-os instead of chaosblade, in fact the parameter that blade happens first to chaos_os is completely correct, but chaos_os screwed everything up,

The call stack of the problem is like this main.main -> cpu.(*cpuExecutor).Exec -> cpu.(*cpuExecutor).stop -> exec.Destroy. The uid setting in main.main is already wrong, But the actual problem is in exec.Destroy, Destroy does not consider uid at all when deleting exp, and directly deletes all processes with "chaos_os" and "cpu fullload" strings in Precossname.

I am solving this problem.

**Comment by Super-long** [comment]
My idea is to divide into two steps, the first step is to correctly parse the uid in main.main, and the second is to add a function to delete the specified uid process in chaosblade-exec-os/exec/exec.go. what do you think of mr xcaspar? @xcaspar

**Comment by Super-long** [comment]
hello everyone, I put the solution in https://github.com/chaosblade-io/chaosblade-spec-go/pull/44

**Comment by Super-long** [comment]
a new solution. @tiny-x @xcaspar

**Comment by Icesource** [comment]
@Super-long Hello, May I ask if your two commits have dependencies？ 
https://github.com/chaosblade-io/chaosblade-spec-go/pull/44
https://github.com/chaosblade-io/chaosblade-exec-os/pull/114
The 114 PR depends on 44 PR？

**Comment by Icesource** [comment]
@Super-long  Could you please help me review the PR https://github.com/chaosblade-io/chaosblade-exec-os/pull/118 ?
