### ISSUE TITLE
Rel 1.2.0 is not compiling

### ISSUE THREAD

**Issue by skslacker** [chaosblade-io/chaosblade#555]
## Issue Description

Tag v1.2.0 not seem to be compiling

### Describe what happened (or what feature you want)
downloaded the git branch of chaosblade repo "v1.2.0" and updated the make file to point all the 5 repos to v1.2.0 instead of master.   ( I had to do this because, if i point to master, i still get compilation issue in Linux).
line #46,50,54,58,62 were changed from master to v1.2.0

### Describe what you expected to happen
I expected the chaosblade repo to compile successfully, as v1.2.0 is the latest release of all the 5 repos listed in the makefile (chaosblade-exec-os, chaosblade-exec-docker,chaosblade-operator,chaosblade-exec-jvm and chaosblade-exec-cplus)

### How to reproduce it (as minimally and precisely as possible)

1. compile all the 6 repos from master in LINUX or
2. compile all the 6 repos from tag v1.2.0 in LINUX
3. both fails

### Tell us your environment
LINUX

**Comment by BPJ94487** [comment]
Hey, you are probably running into a version issue. The exec-cplus only as a 0.8.0 version so if you point it to 1.2.0 it wont work, you can also just keep this on master since nothing has been added since the last release. I just compiled the new release successfully that way. If you are going to successfully point to 1.3.0 versions you will need to make sure you do this as well. It looks like they also just release exec-jvm 1.3.0. When I compiled it was 1.2.0. I will recompile this afternoon and make sure it works too.  I am not sure about your experience, I am new to this tool, but this repo is developing a lot faster than other ones I have worked with which is really nice. Anyways, I hope this helps

**Comment by BPJ94487** [comment]
In summary, change line 60 from 1.2.0 to 0.8.0 or back to master and it should work.

**Comment by xcaspar** [comment]
This problem has been fixed, please use the master branch or the latest release branch (tag: v1.3.0) to compile.
